spring.profiles.active=local
spring.application.name=smart-finance-tracker-api

#Database
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# API Key from Google AI Studio
spring.ai.google.genai.api-key=
# Model and parameters
spring.ai.google.genai.chat.options.model=
spring.ai.google.genai.chat.options.temperature=
#logging.level.root=debug